-- Q1. What is the total revenue generated by male vs female customer?
select gender, sum(purchase_amount) as revenue
from "Customer"
group by gender
order by revenue desc;

-- Q2. Which customers used a discount but still spend more then the average purchase amount?
select customer_id, purchase_amount
from "Customer"
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from "Customer");

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating" 
from "Customer"
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amount between Standard and Express shipping?
select shipping_type, round(avg(purchase_amount::numeric),2) as "Average Amount"
from "Customer"
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue?
select subscription_status,
count(customer_id) as "Total Customer",
round(avg(purchase_amount::numeric),2) as "Spend",
round(sum(purchase_amount::numeric),2) as "Total Revenue"
from "Customer"
group by subscription_status;

-- Q6. Which 5 products have the highest percentage with discount applied?
select item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from "Customer"
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment?
with customer_type as (
select customer_id,previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases between 2 and 10 THEN 'Returning'
	ELSE 'Loyal'
	END as customer_segment
from "Customer"
)
select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- Q8.What are the top 3 most purchased products within each category?
with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)desc) as item_rank
from "Customer"
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from "Customer"
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group ?
select age_group, sum(purchase_amount) as revenue 
from "Customer"
group by age_group
order by revenue desc;